### ISSUE TITLE
New and comprehensive anon data for staging

### ISSUE THREAD

**Issue by woltsu** [UniversityOfHelsinkiCS/oodikone#1423]
- [x] Setup updater to staging
- [x] Wait until updater has finished updating
- [x] Run updater daily task few times
- [x] Take out DB dump

steps:
- add new database to svm-77
- connect  the new database to replica_db on oodikone-staging (the replica already exists, but it is connected to the real db on svm-77)
- make a new instance of updater (docker) to svm-77 and connect it to the new database you created. The new instance of updater should probably not use same cronjobs for daily update as real data ...
- Set up the updater to get all students
- connect replica_db to oodikone-staging backend
