### ISSUE TITLE
Administrative view: prototyping

### ISSUE THREAD

**Issue by cxcorp** [UniversityOfHelsinkiCS/oodikone#1863]
- [x] Don't include study modules in cds calculations
- [x] Hide charts behind 10cm x 10cm buttons to show each chart, make sure back button works
- [x] Remove hardcoded studyright start date and credit targets, replace with start date + 3.5y and start date + 4.5y or something
    - [x] proto C/C2
    - [x] proto G
- [x] Create infobox, write down exactly what dataset is being used
- [x] proto c: hover label -> highlight row / show tooltip
- [x] Polish sort buttons UI
- [x] C & G tooltips: number format to`{name}: {abs} ({percentage}%)`
  * investigate non-invasive highcharts custom events
- [x] proto c: tooltip positioning not in way of cursor?
- [x] scale credits or target according to enrollments
- [x] fix proto g dates -> 1.8.18
- [x] chart modes: current and include ALL transfers from history
    * WHERE credit.credittypecode IN (4, 9) -- Completed or Transferred AND credit.attainment_date >= $3::TIMESTAMP WITH TIME ZONE
- [x] New sparkline thing combined with area chart per period / other time period
  - [x] Drilldown per-programme
  - [x] Change year labels 2017 2018 2019 -> 1.8.17 1.8.18 1.8.19
- [x] Circular thing
  * [x] Fix credittype = 4
- [x] Circular thing drilldown
  * [x] Fix credittype = 4
- [x] Relative circular thing
- [x] Area chart thing per faculty
  * [x] Dynamic data
  * [x] Swap green/red so green is to the left and red to the right
  * [x] Programme drilldown
- [x] Stacked bar chart abs version of area chart
- [x] Area chart compare data with credits hyväksiluvut test
- [x] Area chart drilldown, per programme
- [x] Area chart relative
  * [x] Dynamic data
- [x] Sparkline graphs
- [x] Sankey graphs for individual program of faculty (PoC!)
