### ISSUE TITLE
Plan a structure for study programmes/course modules

### ISSUE THREAD

**Issue by Ajhaa** [UniversityOfHelsinkiCS/oodikone#2028]
- [x] figure out which information (if any) can be excluded
- [x] trim as many levels as possible
- [x] experiment with different study programmes
- [x] design a database model
