### ISSUE TITLE
student course registrations

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#207]
NOTE! Currently (2018-31-07) the Oodi API returns an empty array for most students through the enrollments endpoint. 

- [x] save course unit realisations found in `/students/:id/enrollments` to new table in DB. 
- [x] save course unit realisations and related enrollments to DB.
- [ ] figure out a way to include the enrolled students in course statistics. 

Note: the student enrollments endpoint returns quite a short list for some students. By using the courseunitrealisations changes since endpoint I was able to find courseunitrealisation resources that had the studentnumber in the students list even though the student did not have that particular courseunitrealisation in their enrollments. I suppose that it would be best to use both endpoints in the updater for getting the enrollment information of students.

Updater should save student course registrations

Course stats and population stats course table should show registered but not participated (failed+passed)
