### ISSUE TITLE
Filter rework

### ISSUE THREAD

**Issue by joonashak** [UniversityOfHelsinkiCS/oodikone#2106]
Rework filters (Population Statistics) to get someone to use them.

- [x] Learn to commit shit.
- [x] Integrate credit gain table filters (#2089).
- [x] Integrate courses of population table filters 
- [x] Finish filter design
- [x] Make filter tray push content to the side rather than being overlayed on top of the content.
- [x] Fix animation issues.
- [x] Take care of #2142 
- [x] Display active filters.
- [x] Refactor hardcoded text away.
- [x] Minimizable filter cards.
- [x] Highlight active filters in some way (bump to top or smth else).
- [x] Integrate Matomo tracking.
- [x] Write tests.
- [x] Refactor to use proper feature toggle.
- [x] #2216
- [x] #2220
- [x] #2251
