### ISSUE TITLE
Update oodikone SIS-apis with new features

### ISSUE THREAD

**Issue by Ajhaa** [UniversityOfHelsinkiCS/oodikone#2393]
Sisu apis are a lot behind the oodi apis

- [x] master/bachelor feature in population
- [x] master/bachelor feature in overviw
- [x] use new population calculation
- [x] transfers in population
- [ ] verify that transfers acually work
