### ISSUE TITLE
Population Statistics MEGATICKET

### ISSUE THREAD

**Issue by joonashak** [UniversityOfHelsinkiCS/oodikone#2501]
Things to be verified

- [x] TKT2019 https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2547
- [x] DATATIEDE2019 https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2547
- [x] correct study_start_date of a studyright https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2554
- [x] check termregistration of a student #2541
- [x] fix updater https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2562
- [x] find out why 4 students missing from tkt-kandi 2019 #2584 and #2585
- [x] students missing from msc data science #2588
- [x]  students missing #2589
