### ISSUE TITLE
Course Statistics MEGATICKET

### ISSUE THREAD

**Issue by Darake** [UniversityOfHelsinkiCS/oodikone#2506]
- [x] TKT perusopinnot **126 missing/14 extra** #2532
- [x] KEK110 **173 missing/209extra** #2637
- [x] Fix search returning 500 from backend #2507 
- [x] Fix search returning an error for some courses #2531
- [x] Fix wrong starting and ending dates in search #2529
- [x] Investigate EoAI start date #2556 
- [x] Missing older attainment for same course #2601
- [x] Search returns an error for combined search of all containing TKT #2609
