### ISSUE TITLE
Student Stats MEGATICKET

### ISSUE THREAD

**Issue by joonashak** [UniversityOfHelsinkiCS/oodikone#2513]
- [x] #2499 Fix some student's student page crashing
- [x] #2514 Fix credit graph total credits count
- [x] #2574 studyrights shown wrong
- [x] #2592 
- [x] #2602
