### ISSUE TITLE
access to teachers: course statistics

### ISSUE THREAD

**Issue by anterogradinen** [UniversityOfHelsinkiCS/oodikone#2670]
Tavoite lisätä kaikki HY:n opettajat Oodikoneen käyttäjiksi (koulutusohjelmien johtoryhmäläiset + HOPS-opettajat). Toistaiseksi ei ole luontevaa keinoa tähän paitsi ottaa käyttäjäryhmäksi tiedekuntien koko henkilöstö all-staff-IAM-ryhmien kautta.

Nämä koottu grp-oodikone-basic-users -ryhmään. Ryhmän ylläpito/editointioikeudet Matti, Joonas (+Tomi ja Antero).

Ideana on, että näille käyttäjille näkyy trends + course statistics, mutta sillä rajauksella, että kurssisuoritukset näkyy vaan jos on suorituksia on lukuvuositasolla kuusi tai enemmän.

Käsitellään ensin Course Statistics -näkymä:
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2716 - Hide student numbers
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2726 - IAM-group access
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2717 - Update backend queries for less than 6 students
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2718 - Tables showing text "less than 6"
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2719 - Graphs showing text "less than 6"
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2744 - Hide faculty and programme stats
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2764 - Hide population button
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2761 - Add disclaimer to totals
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2731 - Cumulative-tab should match grades-tab
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2730 - Change "cumulative" to "attempts"
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2794 - Change logic of Students-tab
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2793 - Grades-tab to be part of Attempts
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2729 - Infoboxes
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2720 - Decide what to do with Populations
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2768 - Make course selection more noticeable
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2721 - Tests

**Comment by anterogradinen** [comment]
#

**Comment by anterogradinen** [comment]
grp-toska on lisätty grp-oodikone-basic-users -ryhmän omistajaksi.
