### ISSUE TITLE
Msc studyright / populations megaticket

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#2747]
Cases found this far (studentnumbers in issues)

- [x] #2745 (oodi-oodikone fakap)
- [x] #2748
- [ ] #2749
- [x] #2750
- [ ] #2771 (oodi-oodikone fakap)
- [ ] #2772 (oodi-oodikone fakap)
- [x] #2773
- [ ] #2781

**Comment by otahontas** [comment]
probably better to handle this without megaticket as index, closing this
