### ISSUE TITLE
MEGATICKET: Update project to use node 14

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#2807]
Checklist. X marks that program is running allright in production (there might be of course some uncatched bugs)

- [x] frontend, runs, no issues faced
- [x] backend - OODI, runs normally
- [x] backend - SIS
- [x] analytics
- [x] userservice
- [x] old updater writer
- [x] updater_api
- [x] updater_scheduler

**Comment by otahontas** [comment]
Sis-updater-scheduler and sis-updater-worker had major issues with newest sequelize version (8.2): see #2808 for more info

**Comment by otahontas** [comment]
check if trends work in sis side

**Comment by otahontas** [comment]
- [] sis-updater-scheduler --> major issues, update postponed 21.4.2021
- [ ] sis-updater-worker --> major issue, update postponed 21.4.2021

moved these to another issues, see #2857 #2856

**Comment by otahontas** [comment]
there shouldn't (TM) be any notable bugs now related to node upgrade
