### ISSUE TITLE
Improve Studyprogramme Overview 

### ISSUE THREAD

**Issue by saarasat** [UniversityOfHelsinkiCS/oodikone#3160]
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3291
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3292
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3293
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3294
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3295
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3296
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3297
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3333
- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3351

- [x] https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3376
- [x] #3377 
- [x] #3378
- [x] #3379 
- [x] #3380
- [x] #3381
- [x] #3393 
- [x] #3397 
- [x] #3399 
- [x] #3405 
- [x] #3406 
- [x] #3410 
- [x] #3411    
- [x] #3407  
- [x] #3391 
- [x] #3392
