### ISSUE TITLE
Connect sis HOPS to student credit tracking in student pages

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#3178]
MVP could be: 
- [x] add hops to updater & sis-db models
- [ ] count percents (how much done of hops) in backend
- [ ] study programme changes https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3533
- [ ] student page changes https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3534
