### ISSUE TITLE
[faculty page]

### ISSUE THREAD

**Issue by anterogradinen** [UniversityOfHelsinkiCS/oodikone#3314]
**To-Do:**
- [x] Navigetable faculty page
- [x] Basic information tab
- [ ] Study programmes and progression tab
- [ ] Informaatioviesti dekanaatille, kun ominaisuus on saatavilla
- [ ] Dekanaatin palautetuokio? tai pelkästään Sami Moisio, Haba ja Maika Strömberg (Antoivat alussa ideoita toteutukseen)

Käyttäjäryhmä: dekaani, varadekaani ja opintoasiainpäällikkö + Hakijapalvelu

Tarve: miten koulutusohjelmilla menee. Kytkös Degree programme overview'hin -> kokoaisi näitä tietoja?
Tarve: monitoroida miten eri valintaväylien kautta tulleet etenevät opinnoissa.

Tavoite: suunnittella tämä näkymä.
Tavoite: Opevaradekaanin haastettelu

**Comment by anterogradinen** [comment]
![image (2)](https://user-images.githubusercontent.com/72501421/170249994-18819423-b072-4b8a-aa6e-7ebad9dbe3c8.png)

**Comment by anterogradinen** [comment]
https://learning.edx.org/course/course-v1:MichiganX+PLAx+3T2016/home
