### ISSUE TITLE
[Studyprogramme overview]: Programme Courses list -tab

### ISSUE THREAD

**Issue by saarasat** [UniversityOfHelsinkiCS/oodikone#3602]
- [x] #3654
- [x] #3640 (for course names and codes)
- [x] #3656
- [x] #3657
- [x] #3658
- [x] #3707
- [x] BUG: switching between normal and academic year resets year filter

Bonus, requires further validation how to do and if it is actual useful:

[IRTISANOMISPERUSTE] Add possibility to show the substitute courses in one line 
- [x] Add csv export
