### ISSUE TITLE
[StudyProgramme] Redo graduation times

### ISSUE THREAD

**Issue by sinikala** [UniversityOfHelsinkiCS/oodikone#3822]
See #3817 and #3331 for how to count master graduation times.

Basic info tab:

- [x] Transform pre-existing data to bar display
- [x] Add break-down (on-time, over time,...)
- [x] Fix counting of absences
- [x] Take into account different goal times
- [x] Separate Bc+Ms and Ms into different graphs for Ms programmes.
- Add 'by starting year' Will not do
- [x] Update tests
- [x] Update info boxes
- [x] Remove old code

Studytracks tab:
Continue to #4025
