### ISSUE TITLE
[Importer-Updater-OpenUni] Fetch disclosure of information

### ISSUE THREAD

**Issue by outisa** [UniversityOfHelsinkiCS/oodikone#4003]
- [x] Make the needed changes to importer
- [x] Make the needed changes to updater
- [x] Finally, the needed changes to everywhere else
