### ISSUE TITLE
[faculty - progress stats] faculty H30 mayhem 

### ISSUE THREAD

**Issue by outisa** [UniversityOfHelsinkiCS/oodikone#4037]
Different progress of the programmes compared to other faculties. 

StudyProgrammes MH30_001 and MH30_003 does not have bachelor programme at all, but one programme: licentiate!

- [x] Perhaps separate these two stats to their own table (licentiate...)
- [x] Adjust the credit limits accordingly
- [x] Check that graduation target times are correct for these two, (most probably they are)
