### ISSUE TITLE
course students page

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#581]
show students of the course, filterable by grade, separatable by studyright, also stats view 

- [x] get data from backend
- [x] ability to present data in frontend
- [x] get jump from course page to population working
- [x] remove tables and columns that make no sense for this query
- [x] minthify the elements so that the page doesn't look like shit

**Comment by esakemp** [comment]
#1015 seems to be same issue

**Comment by esakemp** [comment]
chopped this into smaller issues #1171 #1172
