### ISSUE TITLE
faculty level stats

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#841]
- [x] add data calculation to backend
- [x] ability to present data in frontend
- [x] schedule data calculation in backend. It seems that scheduler isn't running there, so we need to add node cron to the backend itself.
- [x] confirm that the cron job runs the scheduled update in
  - [x] staging
  - [x] production

kurhila:

_aika hyvä feature deksuille/opeusvaradeksuille olis sellanen aggregaattinäkymä, jossa olis oman tiedekunnan koulutusohjelmien koonto, siis jonkinlainen vertailu jostain success-metriikoista, opintopisteet per opiskelija, op per opettajat, failurepros ym._

_Noi vertailun mahdollistavat koosteet olis oikeesti tarpeen siksi että deksut ja rehtoraatti vois laittaa painetta ko tuloksellisuuteen. Tällä hetkellä deksut ja opevaradeksut ei tiedä ollenkaan, että miten omilla menee suhteessa muihin. Eli ei tiedetä, meneekö hyvin vai huonosti. Ja siksi reksi joutuu toistuvasti sanomaan että "pliis, yrittäkää parantaa". Mutta reksi tai deksut ei tiedä, kenen._
