### ISSUE TITLE
Rewrite updater

### ISSUE THREAD

**Issue by sasumaki** [UniversityOfHelsinkiCS/oodikone#862]
Rewrite updater mess as separate services with persistent queues, fault tolerant and better logging.

- [x] Updater api that reads studentnumber from queue and gathers all data for that student from oodi API and passes the data to another queue for writing.

Database writing done TDD to make sure it does everything the old updater did (but better).

- [x] Student

- [x] Course

- [x] Course_disciplines

- [ ] Course_enrollments*

- [x] Course_groups* (created manually)

- [x] Course_providers

- [x] Course_types

- [ ] courserealisations*

- [x] courserealisation_types

- [x] credit

- [x] credit_teachers 

- [x] credit_types

- [x] disciplines

- [x] error_data~

- [x] element_details

- [x] organization

- [x] providers

- [x] semester_enrollments

- [x] semesters

- [x] student_list*

- [x] studyright

- [x] studyright_elements

- [x] studyright_extents

- [x] teacher

- [x] teacher_course_group* ( filled through oodikone )

- [x] transfers

- [x] unit*~

- [x] unit_tag*~

- [x] tag_student*~

- [x] tag*~

(*) means that these had no rows after running old updater with few students
(~) means that these were empty in old DB

WE ALSO NEED A SCHEDULER TO UPDATE STUFF

- [x] update X students periodically
- [x] update meta data periodically
- [x] update studentnumber list periodically
- [x] update providers periodically
- [x] refresh studyright associations periodically
- [x] update productivity 

TODO:

- [x] move updater service to backend so it can share models
- [x] move to staging
- [x] parallel testing with existing updater
- [x] move to production ( SVM-77 )
- [x] hot standby streaming
- [x] Change production backend to connect to hot standby replica.

**Comment by Rochet2** [comment]
Whenever we move to latest updater..
If we use a clean database, we should make sure we get the base database structure from our current production.
The reason for this is that a lot of the foreign keys, indexes and even tables are not defined in the sequelize models (maybe they should be?) and using structure created with force sync is missing a lot of stuff that makes things actually function properly.

**Comment by sasumaki** [comment]
I put us in production before reading this so I guess we're going YOLO

**Comment by esakemp** [comment]
![this-is-fine 0](https://user-images.githubusercontent.com/40692959/60802754-54151900-a182-11e9-8e5a-61f6db65fa4b.jpg)
